version: "3"

services:
  whoami:
    image: ${IMAGE_WHOAMI:-bee42/swarm-mointor:linux-amd64-1.3.0}
    build:
      context: .
      args:
          NODE_BASE_IMAGE: ${NODE_BASE_IMAGE:-node:10.12.0-stretch }
          BASE_IMAGE: ${BASE_IMAGE:-node:10.12.0-alpine}