version: "2"

services:
  registry:
    container_name: docker-registry
    restart: always
    image: registry:2.6.2
    ports:
      - 5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./registry:/var/lib/registry
